### ISSUE TITLE
Easy quantity control for thrown weapons/explosives

### ISSUE THREAD

**Issue by teppuM** [Muttley/foundryvtt-fallout#42]
Some way of easily being able to adjust the quantity of explosive/thrown weapons when used would be a delight. As it is now, I need to edit the item to even view the quantity of how many a party member has and subtract from there.

**Comment by Muttley** [comment]
This would be fairly tricky to do without a major overhaul.

I think a good work around right now would be to have a dummy weapon called something like "Throwing Knives" which is set to use a new Ammo type called "Throwing Knife".  You can set the weight/cost/quantity/etc on the ammo instead of the weapon for encumbrance purposes, and when it's rolled it will automatically reduce the "Throwing Knife" ammo count.

This would work for grenades/explosives too.

**Comment by Muttley** [comment]
I'm going to close this as the proposed work-around is probably the best/correct way to handle this.
